apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: Hello from App3.
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app-three

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app-three
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`app3.com`) 
    kind: Rule
    services:
    - name: app-three
      port: 80
