apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: Hello from App1.
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app-one

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app-one
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`app1.com`) 
    kind: Rule
    priority: 2
    services:
    - name: app-one
      port: 80
