apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: Hello from App2.
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app-two

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app-two
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`app2.com`) 
    kind: Rule
    priority: 3
    services:
    - name: app-two
      port: 80
