# -*- mode: ruby -*-

# Machines configurations
SERVICES = {
  'server' => {
    ip: '192.168.56.110',
  }
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.box_version = "202510.26.0"

  # Change the hostname with the login of someone
  config.vm.define "pioupiaS" do |server|
    server.vm.hostname = "pioupiaS"
    server.vm.network "private_network", ip: SERVICES['server'][:ip]

    server.vm.provision "shell",
      path: "https://get.k3s.io",
      env: {
        "INSTALL_K3S_EXEC" => "server --cluster-init -i #{SERVICES['server'][:ip]} --write-kubeconfig-group vagrant --write-kubeconfig-mode 640"
      }

    # Install helm
    server.vm.provision "shell", path: "./scripts/installer.sh"

    server.vm.provision "file", source: "./confs/traefik-config.yaml", destination: "/dev/shm/traefik-config.yaml"
    server.vm.provision "shell", inline: "kubectl apply -f /dev/shm/traefik-config.yaml"

    # Upload apps configuration files
    server.vm.provision "file", source: "./confs/app-one.yaml", destination: "/dev/shm/app-one.yaml"
    server.vm.provision "file", source: "./confs/app-two.yaml", destination: "/dev/shm/app-two.yaml"
    server.vm.provision "file", source: "./confs/app-three.yaml", destination: "/dev/shm/app-three.yaml"

    server.vm.provision "shell", inline: <<-SHELL
      # Wait for traefik to be setup properly (CRDs setup issues)
      until kubectl get crd ingressroutes.traefik.io >/dev/null 2>&1; do
        sleep 2
      done

      sleep 2

      kubectl apply -f /dev/shm/app-one.yaml
      kubectl apply -f /dev/shm/app-two.yaml
      kubectl apply -f /dev/shm/app-three.yaml
SHELL


    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.name = "pioupiaS"
    end
  end
end
