# -*- mode: ruby -*-

# Machines configurations
SERVICES = {
  'server' => {
    ip: '192.168.56.110',
  },
  'worker' => {
    ip: '192.168.56.111',
  }
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  # Provisionning with shell on both server and worker
  config.vm.provision "shell", path: "./scripts/installer.sh"

  # Change the hostname with the login of someone
  config.vm.define "pioupiaS" do |server|
    server.vm.hostname = "pioupiaS"
    server.vm.network "private_network", ip: SERVICES['server'][:ip]

    server.vm.provision "file", source: "./confs/k3s_server.service", destination: "/etc/systemd/system/k3s.service"

    server.vm.provision "shell", inline: <<-SHELL
      sudo -- bash -c 'echo "SERVER_IP=#{SERVICES['server'][:ip]}" >> /etc/systemd/system/k3s.service.env'
      sudo systemctl start k3s
      sudo systemctl enable k3s
SHELL

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "pioupiaS"
    end
  end
end
