# -*- mode: ruby -*-

# Machines configurations
SERVICES = {
  'server' => {
    ip: '192.168.56.110',
  },
  'worker' => {
    ip: '192.168.56.111',
  }
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"
  config.vm.box_version = "20251117.2299.0"

  config.vm.synced_folder ".", "/vagrant/shared", create: true, type: "virtualbox"

  # Provisionning with shell on both server and worker
  config.vm.provision "shell", path: "./scripts/installer.sh"

  # Change the hostname with the login of someone
  config.vm.define "pioupiaS" do |server|
    server.vm.hostname = "pioupiaS"
    server.vm.network "private_network", ip: SERVICES['server'][:ip]

    server.vm.provision "shell", path: "https://get.k3s.io"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "pioupiaS"
    end
  end
  
  config.vm.define "pioupiaSW" do |worker|
    worker.vm.hostname = "pioupiaSW"
    worker.vm.network "private_network", ip: SERVICES['worker'][:ip]

    worker.vm.provision "shell", path: "https://get.k3s.io"

    worker.vm.provision "file", source: "./confs/k3s_worker.service", destination: "/tmp/k3s.service"

    worker.vm.provision "shell", inline: <<-SHELL
      sudo mv "/tmp/k3s.service" /etc/systemd/system/k3s.service

      sudo -- bash -c 'echo "SERVER_URI=https://#{SERVICES['server'][:ip]}:6443" >> /etc/systemd/system/k3s.service.env'
      sudo -- bash -c 'echo "WORKER_IP=#{SERVICES['worker'][:ip]}" >> /etc/systemd/system/k3s.service.env'
SHELL

    worker.vm.provision "shell", path: "./scripts/worker_configuration.sh", env: { "SERVER_IP" => SERVICES['server'][:ip] }

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.name = "pioupiaSW"
      vb.cpus = 1
    end
  end

end
