# -*- mode: ruby -*-

# Machines configurations
SERVICES = {
  'server' => {
    ip: '192.168.56.110',
  },
  'worker' => {
    ip: '192.168.56.111',
  }
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.box_version = "202510.26.0"

  config.vm.synced_folder ".", "/vagrant/shared", create: true, type: "virtualbox"

  config.vm.define "pioupiaS" do |server|
    server.vm.hostname = "pioupiaS"
    server.vm.network "private_network", ip: SERVICES['server'][:ip]

    server.vm.provision "shell",
      path: "https://get.k3s.io",
      env: {
        "INSTALL_K3S_EXEC" => "server --cluster-init -i #{SERVICES['server'][:ip]}"
      }

    server.vm.provision "shell", path: "./scripts/server_configuration.sh"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4069
      vb.cpus = 2
      vb.name = "pioupiaS"
    end
  end

  config.vm.define "pioupiaW" do |worker|
    worker.vm.hostname = "pioupiaW"
    worker.vm.network "private_network", ip: SERVICES['worker'][:ip]

    worker.vm.provision "shell",
      path: "./scripts/worker_configuration.sh",
      env: {
        "SERVER_IP" => SERVICES['server'][:ip],
        "WORKER_IP" => SERVICES['worker'][:ip]
      }

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 4069
      vb.cpus = 2
      vb.name = "pioupiaW"
    end
  end

end
